### ISSUE TITLE
微信小程序不能搜到设备

### ISSUE THREAD

**Issue by pyt618673** [Frspble/SmartMatrix_Arduino#1]
安卓手机，前几天还好好的，上周5早上8点左右，我就用小程序进去设置，但是搜索不到设备，进不去配置界面，今天2台时钟都不能进配置界面去了

**Comment by Frspble** [comment]
线上的小程序之前一直没动过，刚刚才推送了最新的适配iOS的版本。请再次尝试，检查你的蓝牙是否开启，小程序蓝牙权限是否授予，并且确保时钟设备没有被其它设备连接。
